version: "3"
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: "python app.py"
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  # queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'python -u consumer.py'
  #   depends_on:
  #     - db

  db:
    image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: main
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
