version: "3.9"

services:
  flask:
    restart: always
    environment:
      RABBITMQ_URI: "amqps://sxhupzyl:6qwtiY5A6CJKv3PTVQY651zRzHAb5nib@armadillo.rmq.cloudamqp.com/sxhupzyl"
    build:
      context: .
      dockerfile: Dockerfile
    command: "python app.py"
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - flask_db
    networks:
      - my_network

  queue:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - flask_db
    networks:
      - my_network

  flask_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33067:3306"
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_shared_network